#!/bin/sh

# PROVIDE: Kashcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# Kashcoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable Kashcoin service.
# Kashcoin_config (path): Set to /usr/local/etc/Kashcoin.conf by default.
# Kashcoin_user:  The user account Kashcoin daemon runs as. It uses 'root' user by default.
# Kashcoin_group: The group account Kashcoin daemon runs as. It uses 'wheel' group by default.
# Kashcoin_datadir (str): Default to "/var/db/Kashcoin". Base data directory.

. /etc/rc.subr

name=Kashcoin
rcvar=Kashcoin_enable

: ${Kashcoin_enable:=NO}
: ${Kashcoin_config=/usr/local/etc/Kashcoin.conf}
: ${Kashcoin_datadir=/var/db/Kashcoin}
: ${Kashcoin_user="root"}
: ${Kashcoin_group="wheel"}

required_files=${Kashcoin_config}
command=/usr/local/bin/Kashcoind
Kashcoin_chdir=${Kashcoin_datadir}
pidfile="${Kashcoin_datadir}/Kashcoind.pid"
stop_cmd=Kashcoin_stop
command_args="-conf=${Kashcoin_config} -datadir=${Kashcoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

Kashcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${Kashcoin_datadir}
	[ $? -eq 0 ] && chown -R ${Kashcoin_user}:${Kashcoin_group} ${Kashcoin_datadir}
}

Kashcoin_prestart()
{
	if [ ! -d "${Kashcoin_datadir}/." ]; then
		Kashcoin_create_datadir || return 1
	fi
}

Kashcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

Kashcoin_stop()
{
    Kashcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${Kashcoin_config} -datadir=${Kashcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
